INSERT INTO census_info (SUMLEV, REGION, DIVISION, STATE, COUNTY, STNAME, CTYNAME, CENSUS2010POP)
SELECT SUMLEV, REGION, DIVISION, STATE, COUNTY, STNAME, CTYNAME, CENSUS2010POP
FROM census_info;
SELECT COUNT(*) FROM census_info;
